package com.example.geektrust;

public enum PreDefinedStrings {
	
	INVALID_DATE, 
	ADD_TOPUP_FAILED,
	ADD_SUBSCRIPTION_FAILED, 
	SUBSCRIPTIONS_NOT_FOUND, 
	DUPLICATE_CATEGORY, 
	DUPLICATE_TOPUP,
	RENEWAL_REMINDER,
	MUSIC,
	VIDEO,
	PODCAST,
	RENEWAL_AMOUNT;

}
